# -*- coding: utf-8 -*-
"""Simple_Majority_Baseline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UhAOLPL22aoGvMxRA_R8NEX045Ft0xYD

# Simple Baseline Model for Fake Review Detection

Description:
This notebook implements a simple majority-class baseline model for the task of fake review detection. The purpose of this baseline is to establish a lower bound for model performance, against which more sophisticated models can be compared. The notebook uses the provided training and development datasets (train.csv and dev.csv) to compute and evaluate the baseline.

The majority-class baseline provides a quick and interpretable metric for comparison:

It helps understand the inherent difficulty of the task.
It sets a performance benchmark that any meaningful model must surpass.

**Imports**
"""

import numpy as np
from sklearn.metrics import accuracy_score, classification_report

"""**Load Data**"""

# Load datasets
train_data = pd.read_csv('/content/train.csv')
dev_data = pd.read_csv('/content/dev.csv')

"""**Define Classifier**"""

# Determine the majority class in the training data
majority_class = train_data['label'].value_counts().idxmax()
print(f"Majority Class in Training Data: {majority_class}")

# Predict the majority class for all dev set samples
y_pred = [majority_class] * len(dev_data)
y_true = dev_data['label']

# Evaluate the baseline classifier
print("\nAccuracy:", accuracy_score(y_true, y_pred))
print("\nClassification Report:\n", classification_report(y_true, y_pred, zero_division=0))

"""**Limitations**
- The majority-class baseline assumes all samples belong to the most frequent class, ignoring input features.
- It performs poorly on balanced datasets or when minority classes are significant for the task.
- While useful for benchmarking, this approach cannot capture patterns or relationships in the data.
"""